config/routes.rb
require 'sidekiq/web'

Indiegaga::Application.routes.draw do
  root to: 'pages#front'
  get '/home', to: 'artists#index'

  mount Sidekiq::Web, at: '/sidekiq'

  get '/ui', to: 'ui#index'
  get 'ui(/:action)', controller: 'ui'

  resources :artists, only: [:show, :index] do
    collection do
      get :search
    end
    resources :albums, only: [:show]
    resources :reviews, only: [:create]
  end
  resources :genre, only: [:show]

  namespace :admin do
    resources :payments, only: [:index]
    resources :artists, only: [:new, :create]
    resources :albums, only: [:new, :create]
    resources :songs, only: [:new, :create]
  end

  get '/register', to: 'users#new'
  resources :users, only: [:create, :show]
  get 'register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'
  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  resources :sessions, only: [:create]

  get '/playlist', to: "playlist_items#index"
  resources :playlist_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'

  get 'favorties', to: 'favs#index'
  resources :favs, :only: [:create, :destroy]

  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]

  get 'forgot_password', to: 'forgot_passwords#new'
  resource :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :invitations, only: [:new, :create]
  mount StripeEvent::Engine => '/stripe_events'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :genre
  has_many :albums
  has_many :reviews, -> { order(created_at: :desc) }
  has_many :fav_relationships, class_name: "Fav", foreign_key: :icon_id

  mount_uploader :large_cover, LargeCoverUploader
  mount_uploader :small_cover, SmallCoverUploader

  validates_presence_of :name, :bio, :website, :year_created

  def self.search_by_name(search_term)
    return [] if search_term.blank?
    where("name ILIKE ?", "%#{search_term}%").order("created_at DESC")
  end

  def rating
    reviews.average(:rating).round(1) if reviews.average(:rating)
  end

end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < AdminsController
  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      flash[:success] = "You have successfully added '#{@artist.name}'."
      redirect_to new_admin_artist_path
    else
      flash[:error] = "Opps - the artist was not added properly"
      render :new
    end
  end

  private

  def artist_params
    params.require(:artist).permit!
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
    @genres = Genre.all
  end

  def show
    @artist = ArtistDecorator.decorate(Artist.find(params[:id]))
    @albums = @artist.albums
    @reviews = @artist.reviews
  end

  def search
    @results = Artist.search_by_name(params[:search_term])
  end
end

app/views/artists/index.html.haml
- @genres.each do |genre|
%article.video_category
  %header
    %h3= link_to genre.name, genre_path(genre)
  .videos.row
    - genere.recent_artists.each do |artist|
      .video.col-sm-2
        = link_to image_tag(artist.small_cover), artist

app/views/artists/search.html.haml
%article.video.category
  - @results.each do |artist|
    .video.col-sm-2
      - link_to image_tag(artist.small_cover), artist

app/views/artists/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        = image_tag @artist.large_cover.large_version.url
      .video_info.col-sm-3
        %header
          %h3= @artist.name
          %span Genere:
          = @artist.genre_id
          %span Rating:
          = @artist.rating / 5
          %span Formed:
          = @artist.year_created
          %span Webpage:
          = @artist.webpage
          %span Merchandise
          = @artist.store
        %p= @artist.bio
        .actions
          %a.btn.btn-primary(href= "#{@artist.video_url}") Watch Featrued Video
          %a.btn.btn-default(href="") + Follow Artist

        %header
          %h3 Albums (#{@artist.albums})
        %ul
          - @albums.each do |album|
            %article.review
              %li.row
                .col-sm-2
                  %span Year Released: #{album.year}
                .col-sm-8
                  %p
                    = link_to album.title, album

%section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      = form_for [@artist, Review.new] do |f|
        %fieldset
          .form-group
            %label Rate this band
            .row
              .col-sm-3
                = f.select :rating, options_for_artist_reviews
          .form-group
            %label Write Review
            .row
              .col-sm-8
                = f.text_area :content, rows: 6, class: "span6"
        %fieldset.form-group.actions.clearfix
          %input(type="submit" value="Submit" class="btn")
          = link_to "Cancel", @artist
      %header
        %h3 User Reviews (#{@reviews.count})
      %ul
        - @reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %span Rating: #{review.rating} / 5
                  = link_to review.user.full_name, review.user
              .col-sm-8
                %p #{review.content}