config/routes.rb
require 'sidekiq/web'

Indiegaga::Application.routes.draw do
  root to: 'pages#front'
  get '/home', to: 'artists#index'

  mount Sidekiq::Web, at: '/sidekiq'

  get '/ui', to: 'ui#index'
  get 'ui(/:action)', controller: 'ui'

  resources :artists, only: [:show, :index] do
    collection do
      get :search
    end
    resources :albums, only: [:show]
    resources :reviews, only: [:create]
  end
  resources :genre, only: [:show]

  namespace :admin do
    resources :payments, only: [:index]
    resources :artists, only: [:new, :create]
    resources :albums, only: [:new, :create]
    resources :songs, only: [:new, :create]
  end

  get '/register', to: 'users#new'
  resources :users, only: [:create, :show]
  get 'register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'
  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  resources :sessions, only: [:create]

  get '/playlist', to: "playlist_items#index"
  resources :playlist_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'

  get 'favorties', to: 'favs#index'
  resources :favs, :only: [:create, :destroy]

  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]

  get 'forgot_password', to: 'forgot_passwords#new'
  resource :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :invitations, only: [:new, :create]
  mount StripeEvent::Engine => '/stripe_events'
end

app/controllers/forgot_passwords_controller.rb
class ForgotPasswordsController < ApplicationController
  def create
    user = User.where(email: params[:email]).first
    if user
      AppMailer.send_forgot_password(user).deliver
      redirect_to forgot_password_confirmation_path
    else
      flash[:error] = params[:email].blank? ? "Email cannot be blank." : "There is no user with that email in that system."
      redirect_to forgot_password_path
    end
  end

  def confirm
  end
end

app/views/forgot_passwords/confirm.html.haml
%section.confirm_password_reset.container
  .row
    .col-sm-10.col-sm-offset-1
      %p We have send an email with instruction to reset your password.

app/views/forgot_passwords/new.html.haml
%section.forgot_password.container
  .row
    .col-sm-10.col-bg-offset-1
      %form.sign_in
      = form_tag forgot_passwords_path, class: "sign_in" do
        %header
          %h1 Forgot Password?
          %p We will send you an email with a link that you can use to reset your password.
        .form-group
          = label_tag :email, "Email Address"
          = text_field_tag :email
        .form-group.action
          %input(type="submit" value="Send Email" class="btn btn-default")

app/views/forgot_passwords/show.html.haml
%section.forgot_password.container
  .row
    .col-sm-10.col-bg-offset-1
      %form.sign_in
        %header
          %h1 Forgot Password?
          %p We will send you an email with a link that you can use to reset your password.
        .form-group
          %label Email Address
          .row
            .col-sm-4
              %input.form-control(type="email")
        .form-group.action
          %input(type="submit" value="Send Email" class="btn btn-default")