config/routes.rb
require 'sidekiq/web'

Indiegaga::Application.routes.draw do
  root to: 'pages#front'
  get '/home', to: 'artists#index'

  mount Sidekiq::Web, at: '/sidekiq'

  get '/ui', to: 'ui#index'
  get 'ui(/:action)', controller: 'ui'

  resources :artists, only: [:show, :index] do
    collection do
      get :search
    end
    resources :albums, only: [:show]
    resources :reviews, only: [:create]
  end
  resources :genre, only: [:show]

  namespace :admin do
    resources :payments, only: [:index]
    resources :artists, only: [:new, :create]
    resources :albums, only: [:new, :create]
    resources :songs, only: [:new, :create]
  end

  get '/register', to: 'users#new'
  resources :users, only: [:create, :show]
  get 'register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'
  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  resources :sessions, only: [:create]

  get '/playlist', to: "playlist_items#index"
  resources :playlist_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'

  get 'favorties', to: 'favs#index'
  resources :favs, :only: [:create, :destroy]

  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]

  get 'forgot_password', to: 'forgot_passwords#new'
  resource :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :invitations, only: [:new, :create]
  mount StripeEvent::Engine => '/stripe_events'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Tokenable

  has_many :reviews, -> {order("created_at DESC")}
  has_many :playlist_items, ->{ order(:position) }
  has_many :following_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :leading_relationships, class_name: "Relationship", foreign_key: :leader_id
  has_many :fan_relationships, class_name: "Fav", foreign_key: :fan_id

  validates_presence_of :email, :password, :full_name
  validates_uniqueness_of :email
  has_secure_password validations: false



  def normalize_playlist_item_positions
    playlist_items.each_with_index do |playlist_item, index|
      playlist_item.update_attributes(position: index+1)
    end
  end

  def queued_song?(song)
    playlist_items.map(&:song).include?(song)
  end

  def follows?(another_user)
    following_relationships.map(&:leader).include?(another_user)
  end

  def can_follow?(another_user)
    !(self.follows?(another_user) || self == another_user)
  end

  def follow(another_user)
    following_relationships.create(leader: another_user) if can_follow?(another_user)
  end

  def deactivate!
    update_column(:active, false)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :require_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    result = UserSignup.new(@user).sign_up(params[:stripeToken], params[:invitation_token])

    if result.successful?
      flash[:success] = "Thank you for joining for Indiegaga! You may sign in now!"
      redirect_to sign_in_path
    else
      flash[:error] = result.error_message
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new_with_invitation_token
  invitation = Invitation.where(token: params[:token]).first
    if invitation
      @user = User.new(email: invitation.recipient_email)
      @invitation_token = invitation.token
      render :new
    else
      redirect_to expired_token_path
    end
  end

  private
  def user_params
    params.require(:user).permit!
  end
end

app/views/users/new.html.haml
%script(type="text/javascript" src="https://js.stripe.com/v2/")

%script(type="text/javascript")Stripe.setPublishableKey("#{ENV['STRIPE_PUBLISHABLE_KEY']}");

= javascript_include_tag 'payment'

%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for @user, html: { class: "form-horizontal", id: "payment-form"} do |f|
        %header
          %h1 Register
        %fieldset
          .col-sm-6
            = f.email_field :email, label: "Email Address"
            = f.password_field :password
            = f.text_field :full_name, label: "Full Name"
            = hidden_field_tag :invitation_token, @invitation_token
        %fieldset.credit_card
          %span.payment-errors
        .form-group
          %label.col-sm-10(for="credit-card-number")Credit Card Number
          .col-sm-6
            %input.form-control.span3#credit-card-number(type="text" data-stripe="number")
        .form-group
          %label.col-sm-10(for="security-code")Security Code
          .col-sm-6
            %input.form-control.span3#security-code(type="text" data-stripe="cvc")
        .form-group
          %label.col-sm-10 Expiration
          .col-sm-3
            = select_month(Date.today, {add_month_numbers: true},  class: 'form-control', data: {stripe: "exp-month"})
          .col-sm-2
            = select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4}, class: 'form-control', data: {stripe: "exp-year"})
        %fieldset.actions.control-group.col-sm-offset-2
        .controls
          %input(type="submit" value="Sign Up" class="btn btn-default")

app/views/users/show.html.haml
%section.user.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email.downcase)}?s=40")
          %h2 #{@user.full_name}'s video collections (#{@user.playlist_items.count})
          = link_to "Follow", relationships_path(leader_id: @user.id), class: "btn-btn-primary", method: :post if current_user.can_follow?(@user)
        %table.table
          %thead
            %tr
              %th(width="30%") Song Title
              %th(width="15%") Album
          %tbody
            - @user.playlist_items.each do |playlist_item|
              %tr
                %td
                  = link_to playlist_item.song.title, playlist_item.song
                %td
                  = link_to playlist_item.song.album.title, playlist_item.song.album

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3 #{@user.full_name}'s Reviews (#{@user.reviews.count})
      %ul
        - @user.reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %p
                  = link_to review.album.title, review.album
                %col Rating: #{review.rating} / 5
              .col-sm-8
                %p= review.content