config/routes.rb
require 'sidekiq/web'

Indiegaga::Application.routes.draw do
  root to: 'pages#front'
  get '/home', to: 'artists#index'

  mount Sidekiq::Web, at: '/sidekiq'

  get '/ui', to: 'ui#index'
  get 'ui(/:action)', controller: 'ui'

  resources :artists, only: [:show, :index] do
    collection do
      get :search
    end
    resources :albums, only: [:show]
    resources :reviews, only: [:create]
  end
  resources :genre, only: [:show]

  namespace :admin do
    resources :payments, only: [:index]
    resources :artists, only: [:new, :create]
    resources :albums, only: [:new, :create]
    resources :songs, only: [:new, :create]
  end

  get '/register', to: 'users#new'
  resources :users, only: [:create, :show]
  get 'register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'
  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  resources :sessions, only: [:create]

  get '/playlist', to: "playlist_items#index"
  resources :playlist_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'

  get 'favorties', to: 'favs#index'
  resources :favs, :only: [:create, :destroy]

  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]

  get 'forgot_password', to: 'forgot_passwords#new'
  resource :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :invitations, only: [:new, :create]
  mount StripeEvent::Engine => '/stripe_events'
end

app/models/playlist_item.rb
class PlaylistItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :song

  delegate :title, to: :song
  delegate :album, to: :song, prefix: :song
  delegate :genre, to: :song

  validates_numericality_of :position, {only_integer: true}

  def genre_name
    album.genre.name
  end

end

app/controllers/playlist_items_controller.rb
class PlaylistItemsController < ApplicationController
  before_filter :require_user

  def index
    @playlist_items = current_user.playlist_items
  end

  def create
    song = Song.find(params[:song_id])
    queue_song(song)
    redirect_to my_playlist_path
  end

  def destroy
    playlist_item = PlaylistItem.find(params[:id])
    playlist_item.destroy if current_user.playlist_item.include?(playlist_item)
    current_user.normalize_playlist_item_positions
    redirect_to my_playlist_path
  end

  def update_playlist
    begin
      update_playlist_items
      current_user.normalize_playlist_item_positions
    rescue ActiveRecord::RecordInvalid
      flash[:error] = "Invalid position number. Please try again."
    end
    redirect_to my_playlist_path
  end


  private

  def queue_song(song)
    PlaylistItem.create(song: song, user: current_user, position: new_playlist_item_position) unless previously_queued_song?(song)
  end

  def new_playlist_item_position
    current_user.playlist_items.count + 1
  end

  def previously_queued_song?(song)
    current_user.playlist_items.map(&:song).include?(song)
  end

  def update_playlist_items
    ActiveRecord::Base.transaction do
      params[:playlist_items].each do |playlist_item_data|
        playlist_item = PlaylistItem.find(playlist_item_data["id"])
        queue_item.update_attributes!(position: playlist_item_data["position"]) if playlist_item.user == current_user
      end
    end
  end
end

app/views/playlist_items/index.html.haml
%section.my_queue.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %h2 My Playlist
        = form_tag update_playlist_path do
          %table.table
            %thead
              %tr
                %th(width="10%") List Order
                %th(width="30%") Song Title
                %th(width="20%") Album Title
                %th(width="10%") Play
                %th(width="15%") Genre
                %th(width="15%") Remove
            %tbody
              - @playlist_items.each do |playlist_item|
                %tr
                  = hidden_field_tag "playlist_items[][id]", playlist_item.id
                  %td= text_field_tag "playlist_items[][position]", playlist_item.position, data: {song_id: playlist_item.song.id}
                  %td
                    = link_to playlist_item.song_title, playlist_item.song.url
                  %td
                    = button_to "Play", playlist_item.song.url, class: "btn btn-default"
                  %td
                    = link_to playlist__item.genre_name, playlist_item.genre
                  %td
                    = link_to playlist_item, method: :delete do
                      %i.glyphicon.glyphicon-remove
        = submit_tag "Update Playlist", class: "btn btn-default"